# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocovsh < Formula
  desc "Go Coverage in your terminal: a tool for exploring Go Coverage reports from the command line"
  homepage "https://github.com/orlangure/gocovsh"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/orlangure/gocovsh/releases/download/v0.4.0/gocovsh_0.4.0_darwin_arm64.tar.gz"
      sha256 "69c37a1bb943d5b9f4ca94c773e065d744117cb8b9fb525028daef0228df2068"

      def install
        bin.install "gocovsh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orlangure/gocovsh/releases/download/v0.4.0/gocovsh_0.4.0_darwin_amd64.tar.gz"
      sha256 "3973d081f94df3e15be04f81574e427cacb3849302ae6b0fe5396ffd02066f52"

      def install
        bin.install "gocovsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/orlangure/gocovsh/releases/download/v0.4.0/gocovsh_0.4.0_linux_amd64.tar.gz"
      sha256 "554c94fa6361f0597c81de213205b21ecbd5e56d6d6f64632f6fcf2bc9b4d2d0"

      def install
        bin.install "gocovsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orlangure/gocovsh/releases/download/v0.4.0/gocovsh_0.4.0_linux_arm64.tar.gz"
      sha256 "7d7c1c40cf70f24eac5a18f1d0de76b6b94069767d776b3fec94a56b66b294b3"

      def install
        bin.install "gocovsh"
      end
    end
  end
end
