# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocovsh < Formula
  desc "Go Coverage in your terminal: a tool for exploring Go Coverage reports from the command line"
  homepage "https://github.com/orlangure/gocovsh"
  version "0.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orlangure/gocovsh/releases/download/v0.5.1/gocovsh_0.5.1_darwin_amd64.tar.gz"
      sha256 "bda7db97d2bf4595df8c9f86734f9611350ca4d10d946c6e4605663ec244072a"

      def install
        bin.install "gocovsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orlangure/gocovsh/releases/download/v0.5.1/gocovsh_0.5.1_darwin_arm64.tar.gz"
      sha256 "990a4c04478f8e2478da7d37f7c875c6199f28f67ad8f3857f40086841530596"

      def install
        bin.install "gocovsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orlangure/gocovsh/releases/download/v0.5.1/gocovsh_0.5.1_linux_arm64.tar.gz"
      sha256 "7609d49747d903dafd77e4db5fe5514528e960b8630b674d19ae73ab6128caad"

      def install
        bin.install "gocovsh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/orlangure/gocovsh/releases/download/v0.5.1/gocovsh_0.5.1_linux_amd64.tar.gz"
      sha256 "1eed38a3d45cb4fa768fbdaf11e87d685f13cfb606495e6d7aa98f0f7ef6f104"

      def install
        bin.install "gocovsh"
      end
    end
  end
end
